// <auto-generated />
namespace Datalayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class seAgregaBasededatosdeauditoria : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(seAgregaBasededatosdeauditoria));
        
        string IMigrationMetadata.Id
        {
            get { return "201908100531572_se Agrega Base de datos de auditoria"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
